### ISSUE TITLE
Function replacement: duplication of effort?

### ISSUE THREAD

**Issue by jugeeya** [masagrator/ReverseNX#1]
Every function replacement in this code is currently done via: 
```cpp
SaltySDCore_ReplaceImport("_ZN2nn2oe18GetPerformanceModeEv", &GetPerformanceMode0);
SaltySD_function_replace_sym("_ZN2nn2oe18GetPerformanceModeEv", &GetPerformanceMode0);
```

However, these specific functions are likely imports for every game, so the first statement using `ReplaceImport` should be sufficient for your use case. Have you tried without using `function_replace_sym`?

**Comment by masagrator** [comment]
ReplaceImport won't be overwrote by function? Didn't check, I've wanted to be sure that import and function always return the same value. Maybe needlessly or I understand wrong how this code works.

But it works. Issues are for now only on SaltyNX side from what I see.

**Comment by masagrator** [comment]
It looks like it works wthout function_replace_sym.
Pushed commit deleting function_replace_sym lines.

**Comment by jugeeya** [comment]
Cool, as I thought. `function_replace_sym` is more for functions in the `main` that are exported (or just happen to have symbols), rather than `ReplaceImport` which is actually more robust but specifically for imports to the `main` of the game.
