### ISSUE TITLE
Crashing on certain title(s)

### ISSUE THREAD

**Issue by lolihunter-san** [masagrator/ReverseNX#2]
I'm not sure if this happens with other games but so far... I have seen one. Luigi's Mansion 3 (installed .xci version) crash with an "error occured" message if ReverseNX is enabled. I'm not sure about the eshop version but there you go.

**Comment by masagrator** [comment]
This is not ReverseNX fault, but SaltyNX fault. This issue is out of scope for this repo.

I forgot to reply. :D 
Closing.
