### ISSUE TITLE
[BUG] ReverseNX not working at all.

### ISSUE THREAD

**Issue by LivelyZephyrs** [masagrator/ReverseNX#3]
**Informations**

1. FW version (9.1.0)
2. CFW (EmuMMC?) (Atmosphere / No EmuMMC)
3. Version of CFW (0.10.1)
4. Game titleid ( 01007E3006DDA000 / Kirby Star Allies)
5. Version of game described by system f.e. with tinfoil from tinfoil.io (Info -> Application Record -> highest number from "Version" column) (Using Version v5, latest update)

**Attachments**
[saltysd.log](https://github.com/masagrator/ReverseNX/files/4001535/saltysd.log)

**Additional context**
Attempted using KIPS instead of NSP. NSP results in black screen when launching game even with ReverseNX disabled. Game is attempting to be played with cheats. ReverseNX has no effect when enabled during gameplay (Using ReverseNX-Tool to enable mid-game.) Crashes (Displays Atmosphere crash screen) even if cheats are disabled (KIPS); must be disabled before launching game and enabled afterwards (Using ReverseNX-Tool.) (But it has no effect anyway, so no point in doing so.)

**Comment by masagrator** [comment]
1. ReverseNX works only on game boot. It will not work if you will enable it in mid-game. You need to read cheats point again, because you are doing it wrong.
2. Cheats disabling is not working, because it was not updated to support 0.10.0 and newer.

**Comment by masagrator** [comment]
Drafted new ReverseNX-Tool release with added support for Atmosphere 0.10.1+ and repacked NSP-0.1.zip to also support 0.10.1+

**Comment by LivelyZephyrs** [comment]
> Drafted new ReverseNX-Tool release with added support for Atmosphere 0.10.1+ and repacked NSP-0.1.zip to also support 0.10.1+

Just updated and it's still a no go, with both KIPS and NSP. Still crashing even with cheats disabled on launch.
Log (Using KIPS):
[saltysd.log](https://github.com/masagrator/ReverseNX/files/4003270/saltysd.log)

Log (Using NSP):
[saltysd.log](https://github.com/masagrator/ReverseNX/files/4003271/saltysd.log)

If it helps any, I am also using the most up-to date build of Edizon.

**Comment by masagrator** [comment]
From what I see SaltyNX is crashing before detecting game, so you're trying to use cheats without disabling it first. I don't see any trace of disabling ReverseNX at all.

**Comment by masagrator** [comment]
Or you're using too much sysmodules.

**Comment by LivelyZephyrs** [comment]
> From what I see SaltyNX is crashing before detecting game, so you're trying to use cheats without disabling it first. I don't see any trace of disabling ReverseNX at all.

I actually have cheats disabled before launching. Just to be absolutely sure that cheats are disabled however, I double-checked ReverseNX-Tool, and sure enough, cheats are disabled.

Log (NSP):
[saltysd.log](https://github.com/masagrator/ReverseNX/files/4003296/saltysd.log)

Log (KIPS):
[saltysd.log](https://github.com/masagrator/ReverseNX/files/4003299/saltysd.log)

...And to verify that cheats are disabled during launching:
![20191226_142448](https://user-images.githubusercontent.com/14850864/71487963-11a4ce80-27ec-11ea-88f2-b81e5ba5bfbc.jpg)

As for sysmodules, the only modules I load are FTPsnap to delete logs to clear them out, and ReverseNX to verify that cheats are disabled when launching the game, both of which I exit out of properly before launching the game.

**Comment by LivelyZephyrs** [comment]
Well, after some tinkering with my Switch, I finally got ReverseNX to not crash. Turns out the issue wasn't actually with ReverseNX, but rather an update for ReverseNX-Tool came out with Atmosphere 0.10.0+ support. I recently figured out by checking the hbappstore. This bug can be put aside now.

**Comment by masagrator** [comment]
But I mentioned that Tool was updated and you've quoted it and said that it was still not working after updating. So you've only updated ReverseNX, not ReverseNX-Tool?

**Comment by LivelyZephyrs** [comment]
Only updated ReverseNX, yeah. Must've misread it as regular ReverseNX. So sorry for that.
